import { ErrorBase } from "../utils/error";

export type ErrorName =
  | "PE"
  | "SHIMDB"
  | "AMCACHE"
  | "BITS"
  | "ESE"
  | "EVENTLOG"
  | "JUMPLIST"
  | "NTFS"
  | "PREFETCH"
  | "RECYCLEBIN"
  | "REGISTRY"
  | "SEARCH"
  | "SERVICES"
  | "SHELLBAGS"
  | "SHIMCACHE"
  | "SHIMDB"
  | "SHORTCUTS"
  | "SRUM"
  | "TASKS"
  | "USERASSIST"
  | "USERS"
  | "USNJRNL"
  | "LOGONCORRELATION"
  | "CHOCOLATEYINFO"
  | "UPDATESHISTORY"
  | "POWERSHELL"
  | "SHELLITEMS"
  | "MRU"
  | "UAL"
  | "WMIPERSIST"
  | "USB"
  | "SERVICEINSTALL"
  | "OUTLOOK"
  | "WORDWHEEL";

export class WindowsError extends ErrorBase<ErrorName> {}
