import { ErrorBase } from "../utils/error";

export type ErrorName =
  | "PE"
  | "SHIMDB"
  | "AMCACHE"
  | "BITS"
  | "ESE"
  | "EVENTLOG"
  | "JUMPLIST"
  | "NTFS"
  | "PREFETCH"
  | "RECYCLEBIN"
  | "REGISTRY"
  | "SEARCH"
  | "SERVICES"
  | "SHELLBAGS"
  | "SHIMCACHE"
  | "SHIMDB"
  | "SHORTCUTS"
  | "SRUM"
  | "TASKS"
  | "USERASSIST"
  | "USERS"
  | "USNJRNL"
  | "LOGONS"
  | "CHOCOLATEYINFO"
  | "UPDATESHISTORY"
  | "POWERSHELL"
  | "SHELLITEMS"
  | "MRU"
  | "UAL"
  | "WMIPERSIST"
  | "USB"
  | "SERVICEINSTALL"
  | "OUTLOOK"
  | "WORDWHEEL"
  | "BAM"
  | "SCRIPTBLOCK"
  | "FIREWALL_RULES"
  | "EVENTLOG_PROCESSTREE"
  | "WIFI"
  | "ADCERTIFICATES"
  | "RDPLOGONS"
  | "PCA"
  | "EVENTLOG_DEFENDER_QUARANTINE"
  | "EVENTLOG_MSI_INSTALLED";

export class WindowsError extends ErrorBase<ErrorName> { }
